### PR TITLE
Lena's changes !!

### PR DESCRIPTION
**Pull request by eug-lena**
Disclaimer: DO NOT OPEN ON MONDAYS!!!! you have to pinky promise before accepting this PR 💅🏻

### CODE REVIEW

**Comment by IonelPopJara** [comment]
qh1ps6vk2icc1

**Comment by IonelPopJara** [comment]
Good job! Let's hope nobody uses it on mondays

**Comment by wanders00** [comment]
i **AM** gonna use it on monday 😈

**Comment by IonelPopJara** [comment]
> i **AM** gonna use it on monday 😈

No, you won't 
VegetaAngryGIF

**Pull request merged**
